- ğŸ‘‹ Hi, Iâ€™m @TamaraSmit
- ğŸ‘€ Iâ€™m interested in ...learning 
- ğŸŒ± Iâ€™m currently learning ...everyday 
- ğŸ’ï¸ Iâ€™m looking to collaborate on ...jobs 
- ğŸ“« How to reach me ...tamarasmit405@gmail.com 
- ğŸ˜„ Pronouns: ...
- âš¡ Fun fact: ...I love.outdoors 

<!---
TamaraSmit/TamaraSmit is a âœ¨ special âœ¨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
